services:
  db:
    image: postgres
    container_name: creverse_postgres
    ports:
      - '${POSTGRES_PORT:-5433}:5432'
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - creverse-net

  redis:
    image: redis:7-alpine
    container_name: creverse_redis
    ports:
      - '${REDIS_PORT:-6389}:6379'
    command: ['redis-server', '--requirepass', '${REDIS_PASSWORD}']
    networks:
      - creverse-net

  app:
    build:
      context: .
    container_name: creverse_app
    ports:
      - '11223:11223'
    depends_on:
      - db
      - redis
    networks:
      - creverse-net
    environment:
      # DATABASE
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}

      # REDIS
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}

      # JWT 등 기타 필요한 환경변수
      JWT_SECRET: ${JWT_SECRET}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      EXPIRES_IN: ${EXPIRES_IN}

      # AZURE
      AZURE_OPEN_API_VERSION: ${AZURE_OPEN_API_VERSION}
      AZURE_ENDPOINT_URL: ${AZURE_ENDPOINT_URL}
      AZURE_ENDPOINT_KEY: ${AZURE_ENDPOINT_KEY}
      AZURE_OPENAI_DEPLOYMENT_NAME: ${AZURE_OPENAI_DEPLOYMENT_NAME}
      AZURE_ACCOUNT_KEY: ${AZURE_ACCOUNT_KEY}
      AZURE_ACCOUNT_NAME: ${AZURE_ACCOUNT_NAME}
      AZURE_CONNECTION_STRING: ${AZURE_CONNECTION_STRING}
      AZURE_CONTAINER: ${AZURE_CONTAINER}

volumes:
  dbdata:

networks:
  creverse-net:
